/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "my_lib.h"
//#include "stdio.h"

IfxCpu_syncEvent g_cpuSyncEvent = 0;

int core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    unsigned int adcResult;
    unsigned int Result = 0;
    volatile unsigned int adc_state = 0;
    volatile unsigned int potential_meter = 0;
    volatile unsigned int light_sensor = 0;
    volatile unsigned int systick_curr, systick;
    volatile unsigned int systick_prev = SYSTEM_TIMER_0_31_0;

    /* Initialization */
    init_RGBLED();              // Initialize PORT
    init_VADC();                // Initialize VADC

    while(1)
    {
        systick_curr = SYSTEM_TIMER_0_31_0;
        systick = systick_curr - systick_prev;

        if (systick > 100000000 )
        {
            systick_prev = systick_curr;

            if (adc_state == 0)
            {
                adc_state = 1;
                potential_meter = 0;
                for(int i=0; i<16; i++)
                    potential_meter += GetVADC4(7);
                potential_meter >>= 4;
//                printf("Potential Meter: %d\n", potential_meter);
                SetRGBLED(potential_meter);
            }
            else
            {
                adc_state = 0;
                light_sensor = 0;
                for(int i=0; i<16; i++)
                    light_sensor += GetVADC4(6);
                light_sensor >>= 4;
//                printf("Light Sensor: %d\n", light_sensor);
                SetRGBLED(light_sensor);
            }
//            Result = light_sensor + potential_meter;
//            Result = (int)(Result / 2);
//            SetRGBLED(Result);
        }

        VADC_startConversion();

        adcResult = VADC_readResult();
//
//        if(adcResult >= 3096)
//        {
//            PORT02_OMR |= (1<<PS7);            // Set LED RED
//            PORT10_OMR |= (1<<PCL5);           // Clear LED GREEN
//            PORT10_OMR |= (1<<PCL3);           // Clear LED BLUE
//        }
//        else if(adcResult >= 2048)
//        {
//            PORT02_OMR |= (1<<PCL7);            // Clear LED RED
//            PORT10_OMR |= (1<<PS5);             // Set LED GREEN
//            PORT10_OMR |= (1<<PCL3);            // Clear LED BLUE
//        }
//        else if(adcResult >= 1024)
//        {
//            PORT02_OMR |= (1<<PCL7);            // Clear LED RED
//            PORT10_OMR |= (1<<PCL5);            // Clear LED GREEN
//            PORT10_OMR |= (1<<PS3);             // Set LED BLUE
//        }
//        else
//        {
//            PORT02_OMR |= (1<<PCL7);            // Clear LED RED
//            PORT10_OMR |= (1<<PCL5);            // Clear LED GREEN
//            PORT10_OMR |= (1<<PCL3);            // Clear LED BLUE
//        }
    }
    return (1);
}

